package com.posadas.nochespremio.processor;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Properties implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nombre;
   private float valor;

   public Properties()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public float getValor()
   {
      return this.valor;
   }

   public void setValor(float valor)
   {
      this.valor = valor;
   }

   public Properties(java.lang.String nombre, float valor)
   {
      this.nombre = nombre;
      this.valor = valor;
   }

}