package com.posadas.nochespremio.processor;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Properties implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Properties() {
    }

}