package com.posadas.nochespremio.processor;
import com.posadas.nochespremio.dto.AvailavilityResDTO

rule "inicializa parametros"
no-loop true
when 
	eval(true)
then
	PointsCalculator pointsCalculator= new 	PointsCalculator();
	pointsCalculator.setFactorAP(124f);
	pointsCalculator.setFactorCash(125f);
	pointsCalculator.setFactorFR(125f);
	pointsCalculator.setFactorISH(56f);
	pointsCalculator.setFactorMO(26f);
	pointsCalculator.setFactorPoints(21);
	insert(pointsCalculator);
end


rule "calcula response"
no-loop true
when 
	$pointsCalculator: PointsCalculator()
	$availavilityResDTO: AvailavilityResDTO()
then
	$pointsCalculator.getPoints($availavilityResDTO);
	System.out.println($pointsCalculator);
end





