package com.posadas.nochespremio.processor;

rule "inicializa parametros"
no-loop true
when 
	eval(true)
then
	PointsCalculator pointsCalculator= new 	PointsCalculator();
	pointsCalculator.setFactorAP(124f);
	pointsCalculator.setFactorCash(125f);
	pointsCalculator.setFactorFR(125f);
	pointsCalculator.setFactorISH(56f);
	pointsCalculator.setFactorMO(26f);
	pointsCalculator.setFactorPoints(21);
	insert(pointsCalculator);
end




