package com.posadas.nochespremio.processor;
import com.posadas.nochespremio.dto.AvailavilityResDTO

rule "inicializa parametros"
no-loop true
when 
	eval(true)
then
	PointsCalculator pointsCalculator= new 	PointsCalculator();
	pointsCalculator.setFactorAP(3.2f);
	pointsCalculator.setFactorFR(3.10f);
	pointsCalculator.setFactorISH(1.02f);
	pointsCalculator.setFactorMO(3.15f);
	pointsCalculator.setFactorPoints(.55f);
	pointsCalculator.setFactorCash(.45f);
	insert(pointsCalculator);
end


rule "calcula response"
no-loop true
when 
	$pointsCalculator: PointsCalculator()
	$availavilityResDTO: AvailavilityResDTO()
then
	$pointsCalculator.getPoints($availavilityResDTO);
	System.out.println($pointsCalculator);
end





