package com.posadas.nochespremio.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AvailavilityResDTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AvailavilityResDTO() {
    }

}