package com.posadas.promociones;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Promocion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Promocion() {
    }

}