package com.posadas.promociones;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Reservacion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Reservacion() {
    }

}